### ISSUE TITLE
[Feature] delayAfter option about animation

### ISSUE THREAD

**Issue by skie1997** [VisActor/VGrammar#250]
### What problem does this feature solve?

animation will render first and then delay as option

expected effect: 
![20231121163707_rec_](https://github.com/VisActor/VGrammar/assets/40675330/ab1c2fc3-f5dc-48f3-9a52-a8293fa5691d)

### What does the proposed API look like?

delayAfter?: number;

**Comment by xile611** [comment]
fixed in https://github.com/VisActor/VGrammar/pull/252
