### ISSUE TITLE
[Size Optimization] Load scales on demand in vgrammar-core

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VGrammar#266]
### What problem does this feature solve?

vchart 不依赖 vgrammar scale 逻辑，可以减少一部分包体积

### What does the proposed API look like?

none

**Comment by xile611** [comment]
coordinate 也不依赖，coordinate也可以按需

**Comment by xile611** [comment]
fixed in https://github.com/VisActor/VGrammar/pull/270
