### ISSUE TITLE
[Feature] ignore normal animation when other animation is running

### ISSUE THREAD

**Issue by skie1997** [VisActor/VGrammar#492]
### What problem does this feature solve?

- appear 和 normal动画同时配置，两者会依次执行，这种情况下期望忽略这次的normal动画
![20240701150756_rec_](https://github.com/VisActor/VGrammar/assets/40675330/8c463aca-4a6f-417d-bf81-a84063af6471)

**Comment by skie1997** [comment]
讨论后结论：
- 通过给normal动画配置startTime延后一段时间执行，可以强制忽略第一次normal
- 其他情况需要接入后看效果

**Comment by purpose233** [comment]
update 动画和 normal 动画冲突的话感觉只能在 vchart 端或者应用端通过 api 来手动控制动画 stop 和 run？

**Comment by xile611** [comment]
> update 动画和 normal 动画冲突的话感觉只能在 vchart 端或者应用端通过 api 来手动控制动画 stop 和 run？

这样用起来不方便吧
